from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
checks=[]
def ok(c,n):
    checks.append((bool(c),n)); print(("OK  " if c else "FAIL"), n)
version=(ROOT/"VERSION").read_text(encoding="utf-8").strip()
main=(ROOT/"main.py").read_text(encoding="utf-8")
binding=(ROOT/"app/services/multi_store_offer_repair_v14_service.py").read_text(encoding="utf-8")
cross=(ROOT/"app/services/cross_store_search_service.py").read_text(encoding="utf-8")
launcher=(ROOT/"BASLAT_V23_62_75.bat").read_text(encoding="utf-8")
ok(version=="23.62.75","VERSION")
ok("/api/runtime-identity/v236275" in main,"runtime v236275")
ok("/api/runtime-soak-stability/v236275" in main,"soak v236275")
ok("single-source-v236275" in main,"single source v236275")
ok("amazon-binding-first-candidate-real-path-hotfix" in main,"architecture")
ok("V23.62.75 AMAZON BINDING REAL-PATH DETAIL CAP" in binding,"real binding path cap marker")
ok('if definition.code == "amazon" and len(candidate_urls) > 1:' in binding,"amazon binding cap condition")
ok("candidate_urls = candidate_urls[:1]" in binding,"binding slices to first candidate")
cap_pos=binding.find("V23.62.75 AMAZON BINDING REAL-PATH DETAIL CAP")
scrape_pos=binding.find("ScraperRegistry().scrape(candidate_url)")
ok(cap_pos!=-1 and scrape_pos!=-1 and cap_pos < scrape_pos,"cap runs before scraper")
transfer_pos=binding.find('f"V20.4 scraper aktarımı [{definition.name}]:"')
ok(cap_pos!=-1 and transfer_pos!=-1 and cap_pos < transfer_pos,"cap runs before transfer telemetry")
ok("V23.62.74 AMAZON STRONG-QUERY-ONLY" in cross,"v74 strong query preserved")
ok("V23.62.74 AMAZON SELECTOR-READY SEARCH BUDGET" in cross,"v74 selector search preserved")
ok("V23.62.73 AMAZON STRONGEST-CANDIDATE DETAIL CAP" in cross,"v73 base-path cap preserved")
ok("v23.62.72-18s-wall-clock-shared-detail-recovery-browser-budget" in main,"v72 detail budget metadata preserved")
ok("v23.62.69-jelatin-nano-cam-seramik-film-temperli-cam-hard-reject" in main,"phone accessory gate preserved")
ok('"security_challenge_bypass": "disabled"' in main,"security bypass disabled")
ok('"price_integrity_quarantine": "preserved"' in main,"price integrity preserved")
ok("smoke_test_v23_62_75.py" in launcher,"launcher calls v75 smoke")
ok("23.62.75" in launcher,"launcher version")
failed=[n for c,n in checks if not c]
print(f"V23.62.75 smoke {'OK' if not failed else 'FAIL'} {len(checks)-len(failed)}/{len(checks)}")
raise SystemExit(1 if failed else 0)
